apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-module-deployment
  labels:
    app: chat-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-module
  template:
    metadata:
      labels:
        app: chat-module
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: chat-module
        image: surajm2w/chat_module_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: dbName
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: DB_PORT	
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: port
        startupProbe:
          tcpSocket:
            port: 443 
          initialDelaySeconds: 10
          periodSeconds: 5      
      
---

apiVersion: v1
kind: Service
metadata:
  name: chat-module-service
spec:
  type: NodePort
  selector:
    app: chat-module
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 443
      nodePort: 30002
