apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-export-deployment
  labels:
    app: order-export
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-export
  template:
    metadata:
      labels:
        app: order-export
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: order-export
        image: surajm2w/order_export:3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: dbName
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: DB_PORT	
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: port
        startupProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5      
      
---

apiVersion: v1
kind: Service
metadata:
  name: order-export-service
spec:
  type: NodePort
  selector:
    app: order-export
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30110
