apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest # image from docker-hub
        ports:
        - containerPort: 80	
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pass	
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password 
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: phpmyadmin-config
              key: PMA_HOST
        - name: PMA_PORT
          valueFrom :     
            configMapKeyRef:
              name: phpmyadmin-config
              key: PMA_PORT
---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  selector: # mysql Pod Should contain same labels
    app: phpmyadmin
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # Use ClusterIP type to expose internally within the cluster
        
