apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: webapp
        image: surajm2w/servicepoints:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 90
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: dbName
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: DB_PORT	
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: port
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: mongo-root-password
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: port       
        - name: CHAT_MODULE_URL
          value: "http://192.168.49.2:30002/"  # Replace with the actual service name
        - name: WEBHOOK_URL
          value: "http://192.168.49.2:30105/"  # Replace with the actual service name
        - name: ORDER_EXPORT_URL
          value: "http://192.168.49.2:30110/"
        startupProbe:
          tcpSocket:
            port: 90
          initialDelaySeconds: 10
          periodSeconds: 5
      
---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 90
      targetPort: 90
      nodePort: 30100
